# Generated by Django 4.1.5 on 2023-01-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
